services:
  web:
    image: web:1.0
    env_file: ../../web.env
    build:
      context: ../../
      dockerfile: server/docker/Dockerfile-web
    volumes:
      - ../../files/:/src/files
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"

