FROM python:3.14-rc-bookworm

# ARG to ENV allows for flexible use between 'docker-compose' and 'docker build'
# docker-compose allows for .env-files
# docker build does not, so --build-args are needed
ARG WEB_SERVER_IP
ARG WEB_SERVER_PORT
ARG WEB_SERVER_DIR

ENV WEB_SERVER_IP="$WEB_SERVER_IP"
ENV WEB_SERVER_PORT="$WEB_SERVER_PORT"
ENV WEB_SERVER_DIR="$WEB_SERVER_DIR"

# files
RUN mkdir /src
COPY server/start_server.sh /src/server/start_server.sh
COPY setup.src.sh /src/setup.src.sh
RUN chmod +x /src/server/start_server.sh

# http version
RUN echo "HTTP 1.0 - http.server" > README.md

# script sourcing
WORKDIR /src/server/

# start web server
ENTRYPOINT ["/src/server/start_server.sh"]
