FROM python:3.14-rc-bookworm

# config
ENV WEB_SERVER_IP="0.0.0.0"
ENV WEB_SERVER_PORT="8889"
ENV WEB_SERVER_DIR="/src/files"

# convenience
RUN apt-get update && apt-get install -y vim

# server
RUN mkdir -p /app/server/src/
COPY server/requirements.txt /app/server/requirements.txt
COPY server/src/ /app/server/src/
RUN pip3 install --no-cache-dir -r /app/server/requirements.txt \
    && chmod +x /app/server/src/server.py \
    && echo "Using: BaseHTTPRequestHandler" > README.md \
    && echo "HTTP: 1.1" >> README.md

# start web server
EXPOSE 8889
WORKDIR /app/server/src/
ENTRYPOINT ["/app/server/src/server.py"]
