FROM python:3.14-rc-bookworm

# config
ENV WEB_SERVER_IP="0.0.0.0"
ENV WEB_SERVER_PORT="8889"
ENV WEB_SERVER_DIR="/src/files"

# server
RUN mkdir -p /app/server/src/ \
    && mkdir -p /app/server/requirements/
COPY server/requirements/ /app/server/requirements/
COPY server/src/ /app/server/src/

# requirements
# hadolint ignore=DL3008
RUN ls /app/server/requirements
RUN apt-get update \
    && \
    { \
        while read -r req; do \
            apt-get -y --no-install-recommends install "${req}"; \
        done < /app/server/requirements/apt-requirements.txt; \
    } \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir -r /app/server/requirements/py-requirements.txt

# server
RUN chmod +x /app/server/src/server.py \
    && echo 2"Using: BaseHTTPRequestHandler" > README.md \
    && echo "HTTP: 1.1" >> README.md

# start web server
EXPOSE 8889
WORKDIR /app/server/src/
ENTRYPOINT ["/app/server/src/server.py"]
